# Generated by Django 3.2.9 on 2023-03-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo_text',
            field=models.CharField(max_length=250),
        ),
    ]
